name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, nuxt-prisma ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NUXT_APP_BASE_URL: ${{ vars.NUXT_APP_BASE_URL }}
      DATABASE_URL: ${{ vars.DATABASE_URL }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run generate
      env:
        NUXT_APP_BASE_URL: ${{ vars.NUXT_APP_BASE_URL }}
        DATABASE_URL: ${{ vars.DATABASE_URL }}
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist